### PR TITLE
Adds some tests for StorageRegistry setKeyString

### PR DESCRIPTION
**Pull request by devguydavid**

### CODE REVIEW

**Comment by skylon07** [comment]
# Good work!
Thanks for setting all this up! I had a couple questions about what you did though...
1. You used describe() and test()... Are these both jest functions? I think I knew test() was like it(), but I am unfamiliar with describe()
2. Are the current/final changes the ones that undo all the broken tests? (It looks like it, and you're smart so I figure you'd do that 😉)
3. How exactly do the actions/automatic testings work? Do they only run when you make a pull request, or is it whenever I make a commit? (Haven't had time to look at what you did yet. I'll do that soon.)

**Comment by devguydavid** [comment]
> # Good work!
> Thanks for setting all this up! I had a couple questions about what you did though...
> 
> 1. You used describe() and test()... Are these both jest functions? I think I knew test() was like it(), but I am unfamiliar with describe()

Yes, test() is the same as it(). I should have been consistent... we can fix that.

From what I could tell describe() is just a way to group everything. Specifically, I needed to use beforeEach() which runs before each test within the same describe(). I don't know if that's the only way to do it but it works. :)

> 2. Are the current/final changes the ones that undo all the broken tests? (It looks like it, and you're smart so I figure you'd do that 😉)

Yes.

> 3. How exactly do the actions/automatic testings work? Do they only run when you make a pull request, or is it whenever I make a commit? (Haven't had time to look at what you did yet. I'll do that soon.)

I will write a confluence page describing the testing stuff.

**Comment by devguydavid** [comment]
Added https://davtar.atlassian.net/wiki/spaces/GN/pages/235569157/Unit+Tests

**Comment by devguydavid** [comment]
So once you are happy with this feel free to Approve the merge request. We don't have it set up so that reviews are required to merge PRs but I'll wait for that as a signal you are happy with the code as the repo owner.

**Comment by devguydavid** [comment]
Oh, also note that you can see the tests are fixed in the checks below. "All checks have passed" includes the unit tests.

**Comment by skylon07** [comment]
> So once you are happy with this feel free to Approve the merge request. We don't have it set up so that reviews are required to merge PRs but I'll wait for that as a signal you are happy with the code as the repo owner.

Thanks! Preesh it 😄

**Pull request merged**
